[package]
name = "negie"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "negie"
test = false
bench = false

[dependencies]
nalgebra = {version = "*" }
rand = "0.8"
image = "*"
imageproc = "*"
rand_distr = "0.4.3"
clap = { version = "4.0", features = ["derive"] }
